nim = require("nim")
shadows = require("shadows")
LightWorld = require("shadows.LightWorld")
PolygonShadow = require("shadows.ShadowShapes.PolygonShadow")
Light = require("shadows.Light")
Body = require("shadows.Body")
require "simple-slider"
tileMap = {}
leftX = 0
rightX = 0
bottomY = 0
topY = 0
debug1 = {}
debug2 = {}
lightworld = LightWorld:new()
shadowshapes = Body:new(lightworld)
playerLight = Light:new(lightworld, 512)
worldShadows = {}
worldLights = {}
sliders = {}
projectiles = {}
chatTexts = {}
atlasOffsets = {}